apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==      # base64 de 'root'
  mysql-database: cmVzdG8=           # base64 de 'resto'
  mysql-user: cm9vdA==               # base64 de 'root'
  mysql-password: cm9vdA==           # base64 de 'root'


