apiVersion: v1
kind: Service
metadata:
  name: restaurant-app
spec:
  type: NodePort
  selector:
    app: restaurant-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8089
      nodePort: 30036



