apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
        - name: restaurant-app
          image: rihabboulaares/resto-app:v2
          ports:
            - containerPort: 8089   # MATCH Spring Boot port
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/resto   # mysql = nom du service MySQL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
